export const NO_OP = 'NO_OP';
export const USER_AUTHORIZE = 'USER_AUTHORIZE';
export const USER_INFO = 'USER_INFO';
export const USER_INFO_SUCCESSFUL = 'USER_INFO_SUCCESSFUL';
export const USER_INFO_FAILURE = 'USER_INFO_FAILURE';
export const DROPBOX_OAUTH = 'DROPBOX_OAUTH';
export const DB_ACCOUNT_INFO = 'DB_ACCOUNT_INFO';
