export const NO_OP = 'NO_OP';
export const USER_AUTHORIZE = 'USER_AUTHORIZE';
export const USER_AUTHORIZE_SUCCESSFUL = 'USER_AUTHORIZE_SUCCESSFUL';
export const USER_AUTHORIZE_FAILURE = 'USER_AUTHORIZE_FAILURE';
